# Generated by Django 3.0.6 on 2020-05-21 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('isbn', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('stok', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('harga', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
