# Generated by Django 3.0.6 on 2020-06-12 20:03

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200612_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop.models.upload_path),
        ),
    ]
