# Generated by Django 3.0.6 on 2020-06-19 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200619_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
